### ISSUE TITLE
Anguilliform Swimmer

### ISSUE THREAD

**Issue by rohitroxkp7** [nickabattista/IB2d#24]
Hey @nickabattista 
I have looked at the anguilliform swimmer and went through your publications which are based on the parameter subspaces of the simple Anguilliform swimmer. The Re-in and Re-out depend on the length of the swimmer's body in direct proportion. However, upon closely looking, I noticed that the swimmer's length in certain simulations when I change the Re-in is not exactly the same, instead, It changes quite a bit. [I kept a thread on my screen and actually measured]

The code for testing the swimmer's Lagrangian motion, if studied carefully, reveals that all the endpoints of the head lie in the same straight vertical line instead of moving in a rather circular way. This is changing the length significantly. The interpolation is applied to y only. What about x?. I have attached my revised code in my fork which you may please find in my git hub account. The uploading of simulation results is tough because of the size...however the code can be run.

**Comment by rohitroxkp7** [comment]
The files are in a forked repo in my git account, and located in the folder 'Swimmer_2' in the same folder as 'Swimmer' in matlab folder.

**Comment by nickabattista** [comment]
Hi Rohit,

Thank you for your patience. I have not had a chance to respond to any inquiries. You are correct that the length can vary, unless you modify some of the parameter choices (spring and beam stiffnesses). 

Yes, you can also interpolate between the x-values as well. However, if you look at the two states provided, the x-values are the same between them, so if you include the additional interpolation it will not solve this issue. Just a couple things:

- The purpose of this example was just to create a very idealized, simple anguilliform; it is not meant to provide as robust of dataset as some others (see Borazjani & Sotiropoulos 2009 ([link](https://journals.biologists.com/jeb/article/212/4/576/18956/Numerical-investigation-of-the-hydrodynamics-of)), van Rees et al 2013 ([link](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/abs/optimal-shapes-for-anguilliform-swimmers-at-intermediate-reynolds-numbers/82B0F4B119815A9AB0508E67A582A285)), or Hamlet et al. 2015 ([link](https://www.sciencedirect.com/science/article/pii/S0022519315004245)).

- Also, if you include numerous more intermediate interpolate states, you can help preserve the overall length of the swimmer, i.e., interpolate between 200 states rather than 2.

Thanks, and hope that you're enjoying playing with the code!

**Comment by rohitroxkp7** [comment]
Instead of creating more interpolate states, I elected to preserve the length of the lagrangian body by one single line of code. 
You can find that in the update non-invariant beams file in the following link:
https://github.com/rohitroxkp7/Swimmer-Modified
